### PR TITLE
Update orb tools

### PR DESCRIPTION
**Pull request by kennyadsl**
## Summary

This is an attempt to restore the publishing authorization.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] I have used clear, explanatory commit messages.

The following are not always needed (~cross them out~ if they are not):

- [ ] I have added automated tests to cover my changes.
- [ ] I have attached screenshots to demo visual changes.
- [ ] I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- [ ] I have updated the README to account for my changes.

### CODE REVIEW

**Comment by kennyadsl** [comment]
@elia @waiting-for-dev this is not the fix, though. It passes because I rotated the CIRCLE_TOKEN required on CircleCI to publish the orb.

**Review by elia — APPROVED** [review]
good catch on rotating the token! 🔐

**Comment by kennyadsl** [comment]
Still, actual tests are not passing for some reasons related to the solidus_frontend dependency.

**Comment by waiting-for-dev** [comment]
> Still, actual tests are not passing for some reasons related to the solidus_frontend dependency.

We probably need to merge https://github.com/solidusio/solidus/pull/4873 first

**Pull request merged**
