### PR TITLE
Upgrade orb-tools to v11

### PR DESCRIPTION
**Pull request by elia**
Fixes https://github.com/solidusio/circleci-orbs-extensions/issues/36

### CODE REVIEW

**Comment by kennyadsl** [comment]
@elia thanks! How did you test this?

**Comment by elia** [comment]
@kennyadsl the actual ORB source is the same, we're only upgrading the tooling which is tested by the checks in this PR. But if you prefer I can manually test on an existing extension before merging.

**Comment by kennyadsl** [comment]
I think just a small test to be sure tests are running is enough, thanks!

**Comment by elia** [comment]
@kennyadsl looks like it's working fine

- https://github.com/solidusio-contrib/solidus_subscriptions/compare/elia/tmp-orb-test?expand=1
- https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_subscriptions/760/workflows/1026911a-7767-470d-bd32-a83216792000

**Review by kennyadsl — APPROVED** [review]
Thanks!!!!!!!!!!!

**Pull request merged**
