### PR TITLE
Add linting command

### PR DESCRIPTION
**Pull request by elia**
We have a RuboCop configuration in most extensions, allow to easily add a check for that in the CI

### CODE REVIEW

**Comment by elia** [comment]
I'll add a link to the description pointing at an extension CI trying out the new command soon.

**Comment by elia** [comment]
Here https://app.circleci.com/jobs/github/nebulab/solidus_paypal_commerce_platform/266 ✅

**Comment by kennyadsl** [comment]
It still says Run tests On Solidus Master. I saw you started to work on customizing the message so maybe it's just not yet applied there?

Screenshot 2020-07-06 at 18 40 43

**Comment by elia** [comment]
https://app.circleci.com/pipelines/github/nebulab/solidus_paypal_commerce_platform/132/workflows/7b6b9a3b-609a-439b-a9fd-a7637f30eb9a/jobs/273
https://github.com/nebulab/solidus_paypal_commerce_platform/compare/elia/try-out-the-dev-orb

image

**Pull request merged**
