### PR TITLE
Fix the default rails version

### PR DESCRIPTION
**Pull request by elia**
## Summary

_Take 2_

"master" is not a valid version, switching to `null` hoping that the environment variable will turn out as `nil` in Ruby.

Ref: https://github.com/solidusio/solidus_paypal_commerce_platform/pull/139

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] I have used clear, explanatory commit messages.

The following are not always needed (~cross them out~ if they are not):

- [ ] I have added automated tests to cover my changes.
- [ ] I have attached screenshots to demo visual changes.
- [ ] I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- [ ] I have updated the README to account for my changes.

### CODE REVIEW

**Review by kennyadsl — COMMENTED** [review]
why not starting from a supported version? Like 5.2 or similar?

**Comment by elia** [comment]
@kennyadsl probably would be fine to put something like `> 5.2` but the effect would be the same, we would need to update it over time, and can also be misleading (since it would still install the latest released version).

**Comment by kennyadsl** [comment]
Just wondering if having a stricter version could help bundler resolving dependencies, but other than that, you are right. Up to you!

**Comment by elia** [comment]
The current value was the one we used to workaround an old resolution problem in solidus_dev_support, so it should be rock solid, are you aware of other bugs like that one that are still around?

**Review by kennyadsl — APPROVED** [review]

**Comment by kennyadsl** [comment]
Nope, I recall that workaround, but for some reasons I thought it was still slower than having a decently close version. We can change it later if needed.

**Pull request merged**
